# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1216853be16e56886121a7522751eaec615287957085d9e51f9b8bd9b5890ac89b72a251f338beb43d5b28e88c0b0d15d7d0d07f905f330a1a93e1e24427b633

test:
  secret_key_base: 0416b8c327fa3c04516858b081be2ae6c08384228ccd6a2c4934c67f6bc31dec1aedfc6d46230ffb595ec2f4e6f42eabc9f8f228eac863e7a185ca36135fd636

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
